#!/usr/bin/env bash
set -euo pipefail

# opencode-zen-bridge installer
# Sets up: Go bridge -> systemd user service -> codex provider config.
# Requires: codex CLI + Go >= 1.24 (or a prebuilt binary). No API keys.

echo "==> opencode-zen-bridge installer"

if ! command -v codex >/dev/null 2>&1; then
  echo "ERROR: codex CLI not found on PATH."
  echo "  Install it first, e.g.:  npm install -g @openai/codex"
  exit 1
fi
echo "    codex: $(codex --version 2>/dev/null || echo unknown)"

BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"

if command -v go >/dev/null 2>&1; then
  echo "==> Building bridge with $(go version | awk '{print $3}')"
  (cd "$(dirname "$0")/src" && CGO_ENABLED=0 go build -ldflags="-s -w" -o "$BIN_DIR/opencode-zen-bridge" .)
else
  if [ -x "$BIN_DIR/opencode-zen-bridge" ]; then
    echo "    Go not found; using existing binary at $BIN_DIR/opencode-zen-bridge"
  else
    echo "ERROR: Go toolchain not found and no prebuilt binary at $BIN_DIR/opencode-zen-bridge."
    echo "  Install Go >= 1.24, or copy a linux/$(uname -m) build of the bridge to that path."
    exit 1
  fi
fi

echo "==> Installing systemd user service"
mkdir -p "$HOME/.config/systemd/user"
cat > "$HOME/.config/systemd/user/opencode-zen-bridge.service" <<EOF
[Unit]
Description=OpenCode Zen bridge (codex free DeepSeek V4 Flash)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$BIN_DIR/opencode-zen-bridge
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now opencode-zen-bridge

echo -n "    waiting for bridge on 127.0.0.1:6446"
for i in $(seq 1 20); do
  if curl -sf http://127.0.0.1:6446/v1/models >/dev/null 2>&1; then
    echo " OK"
    break
  fi
  echo -n "."
  sleep 0.5
done
if ! curl -sf http://127.0.0.1:6446/v1/models >/dev/null 2>&1; then
  echo "ERROR: bridge did not come up. Check: journalctl --user -u opencode-zen-bridge -n 50"
  exit 1
fi

echo "==> Writing codex provider config"
CODEX_DIR="$HOME/.codex"
mkdir -p "$CODEX_DIR"
if [ -f "$CODEX_DIR/config.toml" ]; then
  cp "$CODEX_DIR/config.toml" "$CODEX_DIR/config.toml.bak.$(date +%s)"
  echo "    backed up existing config.toml -> config.toml.bak.*"
fi

cat > "$CODEX_DIR/config.toml" <<EOF
# Generated by zen-bridge install.sh
model = "deepseek-v4-flash-free"
model_provider = "zen"
web_search = "disabled"
model_reasoning_effort = "medium"
model_catalog_json = "$HOME/.local/share/opencode/codex-models.json"

[model_providers.zen]
name = "OpenCode Zen (free, via local bridge)"
base_url = "http://127.0.0.1:6446/v1"
wire_api = "responses"
model_context_window = 131072
model_max_output_tokens = 8192

[projects."$HOME"]
trust_level = "trusted"
EOF

echo "==> Done."
echo ""
echo "Try it:"
echo "  codex exec \"Use the web_search tool to find today's world population, then reply with one sentence.\""
echo ""
echo "Manual (no systemd): $(dirname "$0")/run.sh"
echo "Uninstall:           $(dirname "$0")/uninstall.sh"
