<#
.SYNOPSIS
  opencode-zen-bridge installer for Windows (no WSL required).

.DESCRIPTION
  Cross-platform twin of install.sh. Builds (or reuses) the bridge, registers a
  background "service" via a Scheduled Task, and writes ~\.codex\config.toml.
  The codex config path/format is identical to the Linux/macOS builds.

  Requires: codex CLI on PATH, and Go >= 1.24 (or an existing binary).

  Usage:
    .\install.ps1            # from the cloned/extracted repo (uses .\src)
    <fetch-src> | install.ps1  # one-liner via Invoke-Expression (see README)
#>
[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

$RepoRaw = "https://raw.githubusercontent.com/tejasm-189/codex-zen-bridge/master"
$BridgeName = "opencode-zen-bridge"
$ListenUrl = "http://127.0.0.1:6446/v1/models"

Write-Host "==> opencode-zen-bridge installer (Windows)"

# --- 1. codex must be present ------------------------------------------------
if (-not (Get-Command codex -ErrorAction SilentlyContinue)) {
    Write-Host "ERROR: codex CLI not found on PATH."
    exit 1
}
Write-Host "    codex: $((codex --version 2>$null) -join ' ')"

# --- 2. Determine source dir (local src/ falls back to GitHub fetch) ---------
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$SrcDir = Join-Path $ScriptDir "src"

function Fetch-Src {
    Write-Host "==> No local src/ found; fetching source from $RepoRaw"
    $tmp = Join-Path $env:TEMP "zen-bridge-src-$([guid]::NewGuid())"
    New-Item -ItemType Directory -Force -Path $tmp | Out-Null
    Invoke-WebRequest -UseBasicParsing -Uri "$RepoRaw/src/go.mod"  -OutFile (Join-Path $tmp "go.mod")
    Invoke-WebRequest -UseBasicParsing -Uri "$RepoRaw/src/main.go" -OutFile (Join-Path $tmp "main.go")
    return $tmp
}

if (-not (Test-Path (Join-Path $SrcDir "main.go"))) {
    $SrcDir = Fetch-Src
}

# --- 3. Build or reuse an existing binary ------------------------------------
$BinDir = Join-Path $HOME ".local\bin"
New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
$BridgePath = Join-Path $BinDir "$BridgeName.exe"

if (Get-Command go -ErrorAction SilentlyContinue) {
    Write-Host "==> Building bridge with $((go version | ForEach-Object { $_.Split(' ')[2] }))"
    Push-Location $SrcDir
    try {
        $env:CGO_ENABLED = "0"
        go build -ldflags="-s -w" -o $BridgePath .
        if ($LASTEXITCODE -ne 0) { throw "go build failed" }
    } finally {
        Pop-Location
    }
} elseif (Test-Path $BridgePath) {
    Write-Host "    Go not found; using existing binary at $BridgePath"
} else {
    Write-Host "ERROR: Go toolchain not found and no binary at $BridgePath."
    exit 1
}

function Test-Bridge {
    try {
        Invoke-WebRequest -UseBasicParsing -Uri $ListenUrl -TimeoutSec 2 | Out-Null
        return $true
    } catch { return $false }
}

# --- 4. Install as a Scheduled Task (starts at log on, keeps running) --------
Write-Host "==> Installing Scheduled Task '$BridgeName'"
$Action = New-ScheduledTaskAction -Execute $BridgePath
$Trigger = New-ScheduledTaskTrigger -AtLogOn
$Settings = New-ScheduledTaskSettingsSet -RestartCount 3 -RestartInterval (New-TimeSpan -Seconds 3) -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
Register-ScheduledTask -TaskName $BridgeName -Action $Action -Trigger $Trigger -Settings $Settings -Description "OpenCode Zen bridge (codex free DeepSeek V4 Flash)" -Force | Out-Null

Write-Host "    starting bridge"
Start-ScheduledTask -TaskName $BridgeName

Write-Host -NoNewline "    waiting for bridge on 127.0.0.1:6446"
$up = $false
for ($i = 0; $i -lt 40; $i++) {
    if (Test-Bridge) { $up = $true; break }
    Write-Host -NoNewline "."
    Start-Sleep -Milliseconds 500
}
if (-not $up) {
    Write-Host ""
    Write-Host "ERROR: bridge did not come up. Check task 'opencode-zen-bridge' in Task Scheduler."
    exit 1
}
Write-Host " OK"

# --- 5. Write codex provider config ------------------------------------------
Write-Host "==> Writing codex provider config"
$CodexDir = Join-Path $HOME ".codex"
New-Item -ItemType Directory -Force -Path $CodexDir | Out-Null
$ConfigPath = Join-Path $CodexDir "config.toml"
if (Test-Path $ConfigPath) {
    $bak = "$ConfigPath.bak.$([DateTimeOffset]::Now.ToUnixTimeSeconds())"
    Copy-Item $ConfigPath $bak
    Write-Host "    backed up existing config.toml -> $bak"
}

$ModelCatalog = Join-Path $HOME ".local\share\opencode\codex-models.json"
$Config = @"
# Generated by zen-bridge install.ps1
model = "deepseek-v4-flash-free"
model_provider = "zen"
web_search = "disabled"
model_reasoning_effort = "medium"
model_catalog_json = "$($ModelCatalog.Replace('\','/'))"

[model_providers.zen]
name = "OpenCode Zen (free, via local bridge)"
base_url = "http://127.0.0.1:6446/v1"
wire_api = "responses"
model_context_window = 131072
model_max_output_tokens = 8192

[projects."$HOME"]
trust_level = "trusted"
"@
Set-Content -Path $ConfigPath -Value $Config -Encoding UTF8

Write-Host "==> Done."
Write-Host ""
Write-Host 'Try it:'
Write-Host '  codex exec "Use the web_search tool to find today''s world population, then reply with one sentence."'
Write-Host ""
Write-Host "Uninstall:          powershell -c `"irm $RepoRaw/uninstall.ps1 | iex`""
